### ISSUE TITLE
GWT3Export does not work when annotation added by XMLMapper annotation processor

### ISSUE THREAD

**Issue by manstis** [treblereel/gwt3-processors#10]
Following https://github.com/treblereel/mapper-xml/pull/81 on `XMLMapper` I get a model class like the following:-
```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "miningBuildTask",
    "dataDictionary",
    "transformationDictionary",
    "model",
    "extension"
})
@XmlRootElement(name = "PMML")
@JsType
@GWT3Export
@XMLMapper
@Configuration(additionalAnnotation = {
    @Configuration.ConfigurationAnnotation(JsType.class),
    @Configuration.ConfigurationAnnotation(GWT3Export.class)
})
public class PMML {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    ...
}
```
The important things to understand are:-
- The class `PMML` is a DTO that has a (un)marshaller generated by the `@XMLMapper` annotation
- The PMML DTO needs to be exposed through JsInterop and the boiler-plate J2CL `@GWT3Export` generated.

This worked fine.

However the generated (un)marshaller also needs exposing through JsInterop and J2CL boiler-plate generated.

This is why I now add the `@Configuration` annotations.

However when I attempt to J2CL compile the application I receive the following error:-
```
/home/manstis/workspaces/git/manstis/marshaller/marshaller-api/target/gwt3BuildCache/0.17-SNAPSHOT/marshaller-api-b8fb723b2f15496d22b830c894a5776cbc13fb79/closure-inputs/com/anstis/pmml/model/PMML_XMLMapperImpl.impl.java.js:64: 
Originally at:
/home/manstis/workspaces/git/manstis/marshaller/marshaller-api/target/gwt3BuildCache/0.17-SNAPSHOT/marshaller-api-b8fb723b2f15496d22b830c894a5776cbc13fb79/closure-inputs/com/anstis/pmml/model/PMML_XMLMapperImpl.native_js:1: ERROR - [JSC_UNDEFINED_VARIABLE] variable com_anstis_pmml_model_PMML_XMLMapperImpl is undeclared
  1| const _PMML_XMLMapperImpl = com_anstis_pmml_model_PMML_XMLMapperImpl
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/manstis/workspaces/git/manstis/marshaller/marshaller-api/target/gwt3BuildCache/0.17-SNAPSHOT/marshaller-api-b8fb723b2f15496d22b830c894a5776cbc13fb79/closure-inputs/com/anstis/pmml/model/PMML_XMLMapperImpl.impl.java.js:66: 
Originally at:
/home/manstis/workspaces/git/manstis/marshaller/marshaller-api/target/gwt3BuildCache/0.17-SNAPSHOT/marshaller-api-b8fb723b2f15496d22b830c894a5776cbc13fb79/closure-inputs/com/anstis/pmml/model/PMML_XMLMapperImpl.native_js:3: ERROR - [JSC_UNDEFINED_VARIABLE] variable PMML_XMLMapperImpl is undeclared
  3| goog.exportProperty(_PMML_XMLMapperImpl, 'INSTANCE', PMML_XMLMapperImpl.$static_INSTANCE__com_anstis_pmml_model_PMML_XMLMapperImpl);
     ^^^^^^^^^^^^^^^^^^

2 error(s), 0 warning(s)
```
The files are in the following ZIP:-
[PMML_XMLMapperImpl.zip](https://github.com/treblereel/gwt3-processors/files/6624093/PMML_XMLMapperImpl.zip)

**Comment by manstis** [comment]
See https://github.com/manstis/marshaller/blob/main/marshaller-api/src/main/java/com/anstis/pmml/model/PMML.java#L70

If you clone https://github.com/manstis/marshaller and uncomment the line; you'll get the error.

With the line commented everything is OK (but the marshaller is not automatically plumbed into the JavaScript world).

**Comment by treblereel** [comment]
@manstis hmm, interesting, let me take a closer look ...

**Comment by treblereel** [comment]
@manstis must be fix in https://github.com/treblereel/gwt3-processors/commit/ecd7e02ad898f504c6e523e4ffb8d76d8507ecea

**Comment by treblereel** [comment]
@manstis updated version has been released to sonatype

**Comment by manstis** [comment]
Great. Thank-you @treblereel. I can confirm it works fine now.
