### ISSUE TITLE
KOGITO-5652: GwtExport should use interface name if present

### ISSUE THREAD

**Issue by manstis** [treblereel/gwt3-processors#12]
See https://issues.redhat.com/browse/KOGITO-5652

I have submitted a [PR](https://github.com/treblereel/gwt3-processors/pull/13) with a simple failing unit test.

Fortunately, putting together the test highlighted that it is the package name causing problems and not the interfaces.

Even more fortunate is that I am not a supersticious person so having submitted PR #13 does not faze me!

**Comment by manstis** [comment]
@treblereel I've added another commit to the PR.

The first commit contains a module `interfaces` that shows the package name problem.

The second commit contains another module `interfaces` that shows a subsequent issue. The content of module `interfaces2` is identical to `interfaces` other than the package name is `v10` and not `v1_0`. It also uses `BUNDLE` optimisation in the J2CL plugin.. which could be the cause.. still, it is a bug.

**Comment by treblereel** [comment]
@manstis thanks a million, let me take a look ...

**Comment by treblereel** [comment]
omg, i know it's extrimly late .... 
this issue is fixed in latest release 
there are tests for it https://github.com/treblereel/gwt3-processors/commit/cdd0fddc36e1c50a8d48169adb469b713e598eed

**Comment by manstis** [comment]
Fixed per @treblereel comment.
